name: website
description: This is the official website for EESTEC LC Xanthi.(enjoy)

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.2

environment:
  sdk: ">=3.0.0 <4.0.0"


dependencies:
  flutter_bloc: ^8.1.2
  carousel_slider: ^4.2.1
  dotted_line: ^3.1.0
  flutter_map: ^6.1.0
  sizer: ^2.0.15
  material_design_icons_flutter: ^7.0.7296
  expansion_tile_card: ^3.0.0
  vertical_tab_bar_view: ^0.0.1
  url_launcher: ^6.1.10
  contained_tab_bar_view: ^0.8.0
  wave: ^0.2.0

  timelines: ^0.1.0
  markdown: ^7.0.2
  google_fonts: ^6.2.1
  extended_image: ^8.2.0
  flutter_svg: ^2.0.4
  flutter_staggered_grid_view: 
  share_plus: ^7.2.2
  download: ^1.0.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  

  latlong2: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  assets:
    - assets/homepage/
    - assets/misc/
    - assets/slider/
    - assets/events/
    - assets/sponsors/
    - assets/gallery/
    - assets/annualTeams/
    - assets/board/
    - assets/sponsors/

  uses-material-design: true
