name: website
description: the source code of eestec.ee.duth.gr website

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  carousel_slider: ^4.0.0
  dotted_line: ^3.1.0
  flutter_map: ^0.14.0
  sizer: ^2.0.15
  material_design_icons_flutter: 5.0.5955-rc.1
  expansion_tile_card: ^2.0.0
  vertical_tab_bar_view: ^0.0.1
  url_launcher: ^6.0.13
  contained_tab_bar_view: ^0.8.0
  wave: ^0.2.0
  timelines:
  markdown: ^4.0.1
  google_fonts:
  extended_image: ^6.0.1
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/homepage/
    - assets/misc/
    - assets/slider/
    - assets/events/
    - assets/sponsors/
  uses-material-design: true
